### PR TITLE
Bump SDK to 40

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Closes https://discourse.flathub.org/t/handbrake-gnome-3-36-eol/1253.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by jstebbins** [comment]
Thanks for bringing this to my attention.  I've been on a bit of a vacation from HandBrake development for quite some time. But this is an easy enough thing to take care of.  I'm traveling tomorrow, so won't have time to finish this off till the weekend, but I'll get to it. Would like to do a quick smoke test myself before this gets merged.

**Comment by TheEvilSkeleton** [comment]
I wish you a great time during the travel.

Worst case scenario I will contact the maintainers of Flathub and they'll merge the MR.

**Comment by bilelmoussaoui** [comment]
> I wish you a great time during the travel.
> 
> Worst case scenario I will contact the maintainers of Flathub and they'll merge the MR.

No, HandBrake is entirely handled by it's upstream maintainers.

**Pull request merged**
